# Site Settings
name: FALLENKINGS
title: FALLENKINGS
description: Welcome to our community, we are based from Indonesia and growing community, we have multi gaming community server between osu! and Minecraft, the main community it was osu! private server who it’s the first one in our Country and the sub-community it’s Minecraft with Survival Gamemode, Come and Join Us!
tags:
  - blog
  - minecraft
  - osu!
  - block
  - private
  - server
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
#  - title: Contact
#    url: /contact
  - title: Feed
    url: /feed.xml
  - title: Discord
    url: https://discord.gg/mKBVX2P2Vg
email: support@troke.id
# See: https://disqus.com/
disqus_username: troke12
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: 1682190302867095256


# Social Media Settings
# Remove the item if you don't need it
github_username: qYuki
#facebook_username: datenshicommunity
#twitter_username: twitter_username
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username


# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: false


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: true
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - jekyll-redirect-from
  
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.1
timezone: Asia/Jakarta
